
salesforce:
  username: raghavaraghava159-zhpj@force.com
  password: "![WzdpnuCE9RN0uWV9vo+RUQ==]"
  token: "![lchPml9fpPJJjWJCp9cFBnK3Z8aLt6FiDnZ9RbOgw90=]"
  
  
database:
  username: "sql12792970"
  password: "TZ5xuCv6dq"
  databaseName: "sql12792970"
  host: "sql12.freesqldatabase.com"
  port: "3306"

